---

name: Refresh Pipenv on schedule

on: 
  schedule:
    - cron: "45 23 * * 0"

jobs:
  pipenv-refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python and cache pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "pip"
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv
      - name: Regenerate Pipfile.lock
        run: pipenv update
      - name: Commit and push changes in Pipfile.lock
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Pipfile.lock
          git diff-index --cached --quiet HEAD || git commit -m "Update Pipfile.lock via gh-actions"
          git push
